version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: turnity-db-dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - turnity-network-dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: turnity-pgadmin-dev
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@turnity.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - turnity-network-dev

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: turnity-api-dev
    restart: always
    ports:
      - "3000:3000"
      - "9229:9229" # Para debugging
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - turnity-network-dev
    command: npm run dev

networks:
  turnity-network-dev:
    driver: bridge

volumes:
  postgres_data_dev:
  pgadmin_data_dev: