services:
  db:
    image: postgres:14-alpine
    container_name: turnity-db-dev
    restart: always
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - turnity-network-dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: turnity-pgadmin-dev
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - turnity-network-dev

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: turnity-api-dev
    restart: always
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DATABASE_URL=${DATABASE_URL}
      - TEST_DATABASE_URL=${TEST_DATABASE_URL}


      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_ACCESS_EXPIRY=${JWT_ACCESS_EXPIRY}
      - JWT_REFRESH_EXPIRY=${JWT_REFRESH_EXPIRY}
      
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
    env_file:
      - .env  
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - prisma_dev:/usr/src/app/node_modules/.prisma
    depends_on:
      db:
        condition: service_healthy
    networks:
      - turnity-network-dev
    # COMANDO CON PRISMA GENERATE ANTES DEL SERVER
    command: >
      sh -c "
        echo 'Generating Prisma client...' &&
        npx prisma generate &&
        echo 'Prisma client generated successfully!' &&
        echo 'Starting development server...' &&
        npm run dev
      "

networks:
  turnity-network-dev:
    driver: bridge

volumes:
  postgres_data_dev:
  pgadmin_data_dev:
  prisma_dev: