FROM node:20-alpine

# Instalar OpenSSL y otras dependencias necesarias para Prisma
RUN apk add --no-cache openssl libstdc++ libc6-compat

# Crear el directorio de trabajo
WORKDIR /usr/src/app

# Copiar archivos de dependencias y luego instalarlas
COPY package*.json ./
RUN npm install

# Copiar el resto del proyecto
COPY . .

# Generar cliente de Prisma
RUN npx prisma generate

# Comando para levantar el servicio
CMD ["npm", "run", "dev"]
